patch:
  description: Upsert user management settings for an organization
  tags:
    - Organizations
  summary: Upsert organization user setting
  operationId: OrganizationService_UpsertUserManagementSettings
  parameters:
    - schema:
        type: string
      description: ID of the organization.
      name: organization_id
      in: path
      required: true
  responses:
    '200':
      description: Returns the updated organization setting.
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/organizationsUpsertUserManagementSettingsResponse.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/OrganizationServiceUpsertUserManagementSettingsBody.yaml
    required: true
