import type { Tool } from '../../types/agent-connectors'

export const tools: Tool[] = [
  {
    name: 'greptilmcp_create_custom_context',
    description: `Create a new custom context for an organization to guide Greptile's code review behavior.`,
    params: [
      {
        name: 'body',
        type: 'string',
        required: false,
        description: `The content of the custom context instruction or pattern.`,
      },
      {
        name: 'metadata',
        type: 'object',
        required: false,
        description: `Additional metadata to associate with the custom context.`,
      },
      {
        name: 'scopes',
        type: 'object',
        required: false,
        description: `Scope configuration for where this custom context applies.`,
      },
      {
        name: 'status',
        type: 'string',
        required: false,
        description: `The initial status of the custom context: ACTIVE, INACTIVE, or SUGGESTED. Defaults to ACTIVE.`,
      },
      {
        name: 'type',
        type: 'string',
        required: false,
        description: `The type of custom context: CUSTOM_INSTRUCTION or PATTERN. Defaults to CUSTOM_INSTRUCTION.`,
      },
    ],
  },
  {
    name: 'greptilmcp_get_code_review',
    description: `Get detailed code review information including status, comments, and analysis results.`,
    params: [
      {
        name: 'codeReviewId',
        type: 'string',
        required: true,
        description: `The unique identifier of the code review to retrieve.`,
      },
    ],
  },
  {
    name: 'greptilmcp_get_custom_context',
    description: `Get detailed custom context information including evidence and linked comments.`,
    params: [
      {
        name: 'customContextId',
        type: 'string',
        required: true,
        description: `The unique identifier of the custom context to retrieve.`,
      },
    ],
  },
  {
    name: 'greptilmcp_get_merge_request',
    description: `Get detailed merge request information including metadata, statistics, Greptile comments, and review analysis.`,
    params: [
      {
        name: 'defaultBranch',
        type: 'string',
        required: true,
        description: `The default branch of the repository.`,
      },
      {
        name: 'name',
        type: 'string',
        required: true,
        description: `The repository name (e.g. owner/repo).`,
      },
      {
        name: 'prNumber',
        type: 'number',
        required: true,
        description: `The pull request or merge request number.`,
      },
      {
        name: 'remote',
        type: 'string',
        required: true,
        description: `The git hosting provider: github, gitlab, azure, or bitbucket.`,
      },
      {
        name: 'remoteUrl',
        type: 'string',
        required: false,
        description: `The remote URL of the repository.`,
      },
    ],
  },
  {
    name: 'greptilmcp_list_code_reviews',
    description: `List code reviews with optional filtering by repository, PR number, and review status.`,
    params: [
      {
        name: 'defaultBranch',
        type: 'string',
        required: false,
        description: `Filter by the repository's default branch.`,
      },
      {
        name: 'limit',
        type: 'number',
        required: false,
        description: `Maximum number of results to return (1-100). Defaults to 20.`,
      },
      {
        name: 'name',
        type: 'string',
        required: false,
        description: `Filter by repository name (e.g. owner/repo).`,
      },
      {
        name: 'offset',
        type: 'number',
        required: false,
        description: `Number of results to skip for pagination. Defaults to 0.`,
      },
      {
        name: 'prNumber',
        type: 'number',
        required: false,
        description: `Filter by pull request number.`,
      },
      {
        name: 'remote',
        type: 'string',
        required: false,
        description: `Filter by git hosting provider.`,
      },
      {
        name: 'remoteUrl',
        type: 'string',
        required: false,
        description: `Filter by the remote URL of the repository.`,
      },
      {
        name: 'status',
        type: 'string',
        required: false,
        description: `Filter by code review status.`,
      },
    ],
  },
  {
    name: 'greptilmcp_list_custom_context',
    description: `List organization custom context with optional filtering by type and generation source.`,
    params: [
      {
        name: 'greptileGenerated',
        type: 'boolean',
        required: false,
        description: `Filter by whether the context was generated by Greptile.`,
      },
      {
        name: 'limit',
        type: 'number',
        required: false,
        description: `Maximum number of results to return (1-100). Defaults to 20.`,
      },
      {
        name: 'offset',
        type: 'number',
        required: false,
        description: `Number of results to skip for pagination. Defaults to 0.`,
      },
      {
        name: 'type',
        type: 'string',
        required: false,
        description: `Filter by context type: CUSTOM_INSTRUCTION or PATTERN.`,
      },
    ],
  },
  {
    name: 'greptilmcp_list_merge_request_comments',
    description: `Get all comments for a pull request or merge request, with optional filtering by generation source, addressed status, and date range.`,
    params: [
      {
        name: 'defaultBranch',
        type: 'string',
        required: true,
        description: `The default branch of the repository.`,
      },
      {
        name: 'name',
        type: 'string',
        required: true,
        description: `The repository name (e.g. owner/repo).`,
      },
      {
        name: 'prNumber',
        type: 'number',
        required: true,
        description: `The pull request or merge request number.`,
      },
      {
        name: 'remote',
        type: 'string',
        required: true,
        description: `The git hosting provider: github, gitlab, azure, or bitbucket.`,
      },
      {
        name: 'addressed',
        type: 'boolean',
        required: false,
        description: `Filter by whether the comment has been addressed.`,
      },
      {
        name: 'createdAfter',
        type: 'string',
        required: false,
        description: `Filter comments created after this ISO 8601 datetime.`,
      },
      {
        name: 'createdBefore',
        type: 'string',
        required: false,
        description: `Filter comments created before this ISO 8601 datetime.`,
      },
      {
        name: 'greptileGenerated',
        type: 'boolean',
        required: false,
        description: `Filter by whether the comment was generated by Greptile.`,
      },
      {
        name: 'remoteUrl',
        type: 'string',
        required: false,
        description: `The remote URL of the repository.`,
      },
    ],
  },
  {
    name: 'greptilmcp_list_merge_requests',
    description: `List merge requests/PRs with optional filtering by repository, branch, author, and state.`,
    params: [
      {
        name: 'authorLogin',
        type: 'string',
        required: false,
        description: `Filter by the author's login username.`,
      },
      {
        name: 'defaultBranch',
        type: 'string',
        required: false,
        description: `Filter by the repository's default branch.`,
      },
      {
        name: 'limit',
        type: 'number',
        required: false,
        description: `Maximum number of results to return (1-100). Defaults to 20.`,
      },
      { name: 'name', type: 'string', required: false, description: `Filter by repository name.` },
      {
        name: 'offset',
        type: 'number',
        required: false,
        description: `Number of results to skip for pagination. Defaults to 0.`,
      },
      {
        name: 'remote',
        type: 'string',
        required: false,
        description: `Filter by git hosting provider.`,
      },
      {
        name: 'remoteUrl',
        type: 'string',
        required: false,
        description: `Filter by the remote URL of the repository.`,
      },
      {
        name: 'sourceBranch',
        type: 'string',
        required: false,
        description: `Filter by the source branch of the merge request.`,
      },
      {
        name: 'state',
        type: 'string',
        required: false,
        description: `Filter by merge request state: open, closed, or merged.`,
      },
    ],
  },
  {
    name: 'greptilmcp_list_pull_requests',
    description: `List pull requests with optional filtering by repository, branch, author, and state. Alias for list_merge_requests.`,
    params: [
      {
        name: 'authorLogin',
        type: 'string',
        required: false,
        description: `Filter by the author's login username.`,
      },
      {
        name: 'defaultBranch',
        type: 'string',
        required: false,
        description: `Filter by the repository's default branch.`,
      },
      {
        name: 'limit',
        type: 'number',
        required: false,
        description: `Maximum number of results to return (1-100). Defaults to 20.`,
      },
      { name: 'name', type: 'string', required: false, description: `Filter by repository name.` },
      {
        name: 'offset',
        type: 'number',
        required: false,
        description: `Number of results to skip for pagination. Defaults to 0.`,
      },
      {
        name: 'remote',
        type: 'string',
        required: false,
        description: `Filter by git hosting provider.`,
      },
      {
        name: 'remoteUrl',
        type: 'string',
        required: false,
        description: `Filter by the remote URL of the repository.`,
      },
      {
        name: 'sourceBranch',
        type: 'string',
        required: false,
        description: `Filter by the source branch of the pull request.`,
      },
      {
        name: 'state',
        type: 'string',
        required: false,
        description: `Filter by pull request state: open, closed, or merged.`,
      },
    ],
  },
  {
    name: 'greptilmcp_search_custom_context',
    description: `Search custom context by content using text search.`,
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: `Text query to search custom context content.`,
      },
      {
        name: 'limit',
        type: 'number',
        required: false,
        description: `Maximum number of results to return (1-50). Defaults to 10.`,
      },
      {
        name: 'offset',
        type: 'number',
        required: false,
        description: `Number of results to skip for pagination. Defaults to 0.`,
      },
    ],
  },
  {
    name: 'greptilmcp_search_greptile_comments',
    description: `Search Greptile review comments across all merge requests using text search.`,
    params: [
      {
        name: 'query',
        type: 'string',
        required: true,
        description: `Text query to search Greptile review comments.`,
      },
      {
        name: 'createdAfter',
        type: 'string',
        required: false,
        description: `Filter comments created after this ISO 8601 datetime.`,
      },
      {
        name: 'includeAddressed',
        type: 'boolean',
        required: false,
        description: `Whether to include already-addressed comments in results. Defaults to false.`,
      },
      {
        name: 'limit',
        type: 'number',
        required: false,
        description: `Maximum number of results to return (1-50). Defaults to 10.`,
      },
    ],
  },
  {
    name: 'greptilmcp_trigger_code_review',
    description: `Trigger a Greptile code review for a pull request. Supported on GitHub and GitLab only.`,
    params: [
      {
        name: 'name',
        type: 'string',
        required: true,
        description: `The repository name (e.g. owner/repo).`,
      },
      {
        name: 'prNumber',
        type: 'number',
        required: true,
        description: `The pull request number to trigger a code review for.`,
      },
      {
        name: 'remote',
        type: 'string',
        required: true,
        description: `The git hosting provider. Only github and gitlab are supported.`,
      },
      {
        name: 'branch',
        type: 'string',
        required: false,
        description: `The source branch of the pull request to review.`,
      },
      {
        name: 'defaultBranch',
        type: 'string',
        required: false,
        description: `The default branch of the repository.`,
      },
      {
        name: 'remoteUrl',
        type: 'string',
        required: false,
        description: `The remote URL of the repository.`,
      },
    ],
  },
]
