import type { Tool } from '../../types/agent-connectors'

export const tools: Tool[] = [
  {
    name: 'stripemcp_list_available_accounts_or_orgs',
    description: `Lists all Stripe accounts available in this session with their stripe_context and livemode values. Call this first to get stripe_context and livemode before any account-specific operation. Ask the user which account to use unless already specified, and warn before switching between test mode and live mode.`,
    params: [],
  },
  {
    name: 'stripemcp_manage_stripe_accounts',
    description: `Returns a URL to the Stripe Dashboard where the user can add accounts, remove accounts, or change permissions for this session. Use when the user wants to add, remove, or modify permissions for an account — no need to call list_available_accounts_or_orgs first. After the user confirms they completed their changes, call list_available_accounts_or_orgs to sync the updated account list.`,
    params: [],
  },
  {
    name: 'stripemcp_search_stripe_documentation',
    description: `Search Stripe official documentation and API reference for answers. Use this to look up Stripe concepts, API parameters, error codes, or integration guidance.`,
    params: [
      {
        name: 'question',
        type: 'string',
        required: true,
        description: `The question or topic to search Stripe documentation for.`,
      },
      {
        name: 'language',
        type: 'string',
        required: false,
        description: `Programming language for code examples in results. Defaults to no specific language.`,
      },
      {
        name: 'search_only_api_ref',
        type: 'boolean',
        required: false,
        description: `Set to true to search only the API reference. Set to false (default) to search all documentation including guides and tutorials.`,
      },
    ],
  },
  {
    name: 'stripemcp_send_stripe_mcp_feedback',
    description: `Submit feedback about a Stripe MCP tool experience. Use source=user for feedback from a human, source=agent for feedback generated by an AI agent.`,
    params: [
      {
        name: 'context',
        type: 'string',
        required: true,
        description: `Additional context about what you were trying to do when you used the tool.`,
      },
      {
        name: 'quote',
        type: 'string',
        required: true,
        description: `A direct quote or specific observation about the tool experience.`,
      },
      {
        name: 'sentiment',
        type: 'string',
        required: true,
        description: `Sentiment of the feedback. Valid values: positive, negative, neutral.`,
      },
      {
        name: 'source',
        type: 'string',
        required: true,
        description: `Who generated this feedback. Valid values: user (human feedback), agent (AI-generated feedback).`,
      },
      {
        name: 'tool_name',
        type: 'string',
        required: false,
        description: `Name of the specific Stripe MCP tool this feedback is about.`,
      },
    ],
  },
  {
    name: 'stripemcp_stripe_analytics',
    description: `Analyze Stripe data (e.g. revenue, products, or payments) and run SQL-based reporting queries. Supports ad-hoc SQL (execute_query_run/retrieve_query_run against searchable tables via search_query_tables/retrieve_query_table) and pre-built subscription/billing metric templates (execute_query_template/retrieve_query_template). Monetary values are returned in the smallest currency unit.`,
    params: [
      {
        name: 'intent',
        type: 'string',
        required: true,
        description: `The intent of the tool call.`,
      },
      {
        name: 'livemode',
        type: 'boolean',
        required: true,
        description: `Whether to operate in livemode (true) or test mode/ sandbox (false). Must match the livemode of the stripe_context account.`,
      },
      {
        name: 'stripe_context',
        type: 'string',
        required: true,
        description: `The account to target for this request. Use the \`stripe_context\` value returned by list_available_accounts_or_orgs.`,
      },
      {
        name: 'params',
        type: 'object',
        required: false,
        description: `The parameters for the tool call. Required parameters depend on the intent.`,
      },
    ],
  },
  {
    name: 'stripemcp_stripe_api_details',
    description: `Get the full parameter schema for a specific Stripe API operation. Use stripe_api_search to find the operation ID first (e.g. GetCustomers, PostRefunds), then call this to see all available parameters.`,
    params: [
      {
        name: 'livemode',
        type: 'boolean',
        required: true,
        description: `Whether to operate in livemode (true) or test mode/ sandbox (false). Must match the livemode of the stripe_context account.`,
      },
      {
        name: 'stripe_api_operation_id',
        type: 'string',
        required: true,
        description: `The Stripe API operation ID to get details for. Get valid IDs from stripe_api_search (e.g. GetCustomers, PostRefunds, PostSubscriptions).`,
      },
      {
        name: 'stripe_context',
        type: 'string',
        required: true,
        description: `The account to target for this request. Use the \`stripe_context\` value returned by list_available_accounts_or_orgs.`,
      },
    ],
  },
  {
    name: 'stripemcp_stripe_api_read',
    description: `Execute a read-only (GET) Stripe API operation by its operation ID and parameters. Use stripe_api_search to discover available operations and stripe_api_details to see their parameters before executing.`,
    params: [
      {
        name: 'livemode',
        type: 'boolean',
        required: true,
        description: `Whether to operate in livemode (true) or test mode/ sandbox (false). Must match the livemode of the stripe_context account.`,
      },
      {
        name: 'parameters',
        type: 'object',
        required: true,
        description: `Parameters for the API call. Include path parameters (e.g. 'customer' for /v1/customers/{customer}), query parameters, and body parameters. Array fields (e.g. line_items) must be passed as a JSON array value, not as a plain string.`,
      },
      {
        name: 'stripe_api_operation_id',
        type: 'string',
        required: true,
        description: `The operation ID to execute (e.g. PostCustomers, GetPaymentIntents).`,
      },
      {
        name: 'stripe_context',
        type: 'string',
        required: true,
        description: `The account to target for this request. Use the \`stripe_context\` value returned by list_available_accounts_or_orgs.`,
      },
    ],
  },
  {
    name: 'stripemcp_stripe_api_search',
    description: `Search available Stripe API operations by intent and resource. Returns operation IDs (e.g. PostCustomers, GetSubscriptions) with their HTTP method and parameters — use these with stripe_api_details or stripe_api_read/stripe_api_write.`,
    params: [
      {
        name: 'intent',
        type: 'string',
        required: true,
        description: `The intent of the operation. Examples: create, list, refund.`,
      },
      {
        name: 'livemode',
        type: 'boolean',
        required: true,
        description: `Whether to operate in livemode (true) or test mode/ sandbox (false). Must match the livemode of the stripe_context account.`,
      },
      {
        name: 'resource',
        type: 'string',
        required: true,
        description: `Target resource the operation is looking to manipulate. Examples: customer, payout methods, issuing card transactions.`,
      },
      {
        name: 'stripe_context',
        type: 'string',
        required: true,
        description: `The account to target for this request. Use the \`stripe_context\` value returned by list_available_accounts_or_orgs.`,
      },
      {
        name: 'limit',
        type: 'integer',
        required: false,
        description: `Maximum number of results to return.`,
      },
    ],
  },
  {
    name: 'stripemcp_stripe_api_write',
    description: `Execute a write (POST/DELETE) Stripe API operation by its operation ID and parameters. Use stripe_api_search to discover available operations and stripe_api_details to see their parameters before executing. May require human confirmation for sensitive operations.`,
    params: [
      {
        name: 'livemode',
        type: 'boolean',
        required: true,
        description: `Whether to operate in livemode (true) or test mode/ sandbox (false). Must match the livemode of the stripe_context account.`,
      },
      {
        name: 'parameters',
        type: 'object',
        required: true,
        description: `Parameters for the API call. Include path parameters (e.g. 'customer' for /v1/customers/{customer}), query parameters, and body parameters. Array fields (e.g. line_items) must be passed as a JSON array value, not as a plain string.`,
      },
      {
        name: 'stripe_api_operation_id',
        type: 'string',
        required: true,
        description: `The operation ID to execute (e.g. PostCustomers, GetPaymentIntents).`,
      },
      {
        name: 'stripe_context',
        type: 'string',
        required: true,
        description: `The account to target for this request. Use the \`stripe_context\` value returned by list_available_accounts_or_orgs.`,
      },
      {
        name: 'human_confirmation',
        type: 'object',
        required: false,
        description: `This tool might require human confirmation. To run it, first invoke it with the desired parameters, ignoring the \`approval_token\` parameter. If it requires human confirmation, the response will include an approval request ID and a URL to an approval page for the human to approve the tool call. Present this URL to the human as a clickable markdown link, and after they confirm approval, call the tool again with the same parameters plus \`approval_token\`.`,
      },
    ],
  },
  {
    name: 'stripemcp_stripe_implementation_planner',
    description: `Stripe payment integration planner. Use this BEFORE writing code when the user wants to accept payments, sell products online, set up billing, or build any Stripe integration — it returns use cases, decision trees, documentation links, and a guide_id for follow-up calls. Successor to stripe_integration_recommender.`,
    params: [
      {
        name: 'livemode',
        type: 'boolean',
        required: true,
        description: `Whether to operate in livemode (true) or test mode/ sandbox (false). Must match the livemode of the stripe_context account.`,
      },
      {
        name: 'message',
        type: 'string',
        required: true,
        description: `For new guides: describe the use case or business requirements. For existing guides: provide the latest user response or the full accepted transcript.`,
      },
      {
        name: 'stripe_context',
        type: 'string',
        required: true,
        description: `The account to target for this request. Use the \`stripe_context\` value returned by list_available_accounts_or_orgs.`,
      },
      {
        name: 'accept',
        type: 'boolean',
        required: false,
        description: `Set to true when returning the completed decision tree with your chosen options to receive the finalized integration guide.`,
      },
      {
        name: 'guide_id',
        type: 'string',
        required: false,
        description: `ONLY pass a guide_id that was returned by a previous call to this tool in this conversation. Never fabricate, guess, or reuse guide_ids from other sessions. If you do not have a guide_id from a prior response, omit this field entirely. Invalid guide_ids will be rejected.`,
      },
    ],
  },
]
