type: object
properties:
  code_challenge_length:
    description: Code Challenge Length
    type: integer
    format: int64
    examples:
      - 6
  code_challenge_type:
    description: Code Challenge Type
    $ref: ./connectionsCodeChallengeType.yaml
    examples:
      - NUMERIC
  enforce_same_browser_origin:
    description: Enforce Same Browser Origin
    type: boolean
    examples:
      - true
  frequency:
    description: Link Frequency
    type: integer
    format: int64
    examples:
      - 1
  regenerate_passwordless_credentials_on_resend:
    description: 'Regenerate the '
    type: boolean
    examples:
      - true
  type:
    description: Passwordless Type
    $ref: ./connectionsPasswordlessType.yaml
    examples:
      - LINK
  validity:
    description: Link Validity in Seconds
    type: integer
    format: int64
    examples:
      - 600
