type: object
properties:
  allow_idp_initiated_login:
    description: Allow IDP Initiated Login
    type: boolean
    examples:
      - true
  assertion_encrypted:
    description: Assertion Encrypted
    type: boolean
    examples:
      - true
  certificate_id:
    description: Certificate ID
    type: string
    examples:
      - cer_35585423166144613
  default_redirect_uri:
    description: Default Redirect URI
    type: string
    examples:
      - https://yourapp.com/service/saml/redirect
  force_authn:
    description: Force Authn
    type: boolean
    examples:
      - true
  idp_certificates:
    description: IDP Certificates
    type: array
    items:
      type: object
      $ref: ./connectionsIDPCertificate.yaml
  idp_entity_id:
    description: IDP Entity ID
    type: string
    examples:
      - https://youridp.com/service/saml
  idp_metadata_url:
    description: IDP Metadata URL
    type: string
    examples:
      - https://youridp.com/service/saml/metadata
  idp_name_id_format:
    description: IDP Name ID Format
    $ref: ./connectionsNameIdFormat.yaml
    examples:
      - EMAIL
  idp_slo_request_binding:
    description: IDP SLO Request Binding
    $ref: ./connectionsRequestBinding.yaml
    examples:
      - HTTP_POST
  idp_slo_required:
    description: Enable IDP logout
    type: boolean
    examples:
      - true
  idp_slo_url:
    description: IDP SLO URL
    type: string
    examples:
      - https://youridp.com/service/saml/slo
  idp_sso_request_binding:
    description: IDP SSO Request Binding
    $ref: ./connectionsRequestBinding.yaml
    examples:
      - HTTP_POST
  idp_sso_url:
    description: IDP SSO URL
    type: string
    examples:
      - https://youridp.com/service/saml/sso
  jit_provisioning_with_sso_enabled:
    description: Indicates if Just In Time user provisioning is enabled for the connection
    type: boolean
    examples:
      - true
  saml_signing_option:
    description: SAML Signing Option
    $ref: ./connectionsSAMLSigningOptions.yaml
    examples:
      - SAML_ONLY_RESPONSE_SIGNING
  sp_assertion_url:
    description: SP Assertion URL
    type: string
    examples:
      - https://youridp.com/service/saml/assertion
  sp_entity_id:
    description: SP Entity ID
    type: string
    examples:
      - https://yourapp.com/service/saml
  sp_metadata_url:
    description: SP Metadata URL
    type: string
    examples:
      - https://youridp.com/service/saml/metadata
  sp_slo_url:
    description: Service Provider SLO url
    type: string
    readOnly: true
    examples:
      - https://yourapp.com/sso/v1/saml/conn_1234/slo/callback
  sync_user_profile_on_login:
    description: >-
      Indicates whether user profiles should be synchronized with the identity
      provider upon each log-in.
    type: boolean
    examples:
      - true
  ui_button_title:
    description: UI Button Title
    type: string
    examples:
      - Login with SSO
  want_request_signed:
    description: Want Request Signed
    type: boolean
    examples:
      - true
