type: object
properties:
  authorize_uri:
    description: Authorize URI
    type: string
    examples:
      - https://youridp.com/service/oauth/authorize
  backchannel_logout_redirect_uri:
    description: backchannel logout redirect uri where idp sends logout_token
    type: string
    readOnly: true
    examples:
      - https://yourapp.com/sso/v1/oidc/conn_1234/backchannel-logout
  client_id:
    description: Client ID
    type: string
    examples:
      - oauth_client_id
  client_secret:
    description: Client Secret
    type: string
    examples:
      - oauth_client_secret
  discovery_endpoint:
    description: Discovery Endpoint
    type: string
    examples:
      - https://youridp.com/service/oauth/.well-known/openid-configuration
  idp_logout_required:
    description: Enable IDP logout
    type: boolean
    examples:
      - true
  issuer:
    description: Issuer URL
    type: string
    examples:
      - https://youridp.com/service/oauth
  jit_provisioning_with_sso_enabled:
    description: Indicates if Just In Time user provisioning is enabled for the connection
    type: boolean
    examples:
      - true
  jwks_uri:
    description: JWKS URI
    type: string
    examples:
      - https://youridp.com/service/oauth/jwks
  pkce_enabled:
    description: PKCE Enabled
    type: boolean
    examples:
      - true
  post_logout_redirect_uri:
    description: post logout redirect uri
    type: string
    readOnly: true
    examples:
      - https://yourapp.com/sso/v1/oidc/conn_1234/logout/callback
  redirect_uri:
    description: Redirect URI
    type: string
    examples:
      - https://yourapp.com/sso/v1/oidc/conn_1234/callback
  scopes:
    description: OIDC Scopes
    type: array
    items:
      $ref: ./connectionsOIDCScope.yaml
    examples:
      - - openid
        - profile
  sync_user_profile_on_login:
    description: >-
      Indicates whether user profiles should be synchronized with the identity
      provider upon each log-in.
    type: boolean
    examples:
      - true
  token_auth_type:
    description: Token Auth Type
    $ref: ./connectionsTokenAuthType.yaml
    examples:
      - URL_PARAMS
  token_uri:
    description: Token URI
    type: string
    examples:
      - https://youridp.com/service/oauth/token
  user_info_uri:
    description: User Info URI
    type: string
    examples:
      - https://youridp.com/service/oauth/userinfo
