type: object
title: >-
  WebAuthConfiguration defines WebAuthn (passkeys) configuration limited to RP
  and Attestation
properties:
  attestation:
    $ref: ./WebAuthConfigurationAttestation.yaml
  authenticator_selection:
    $ref: ./WebAuthConfigurationAuthenticatorSelection.yaml
  authenticators:
    $ref: ./WebAuthConfigurationAuthenticators.yaml
  enable_auto_registration:
    description: Enable auto registration for WebAuthn
    type: boolean
  enable_conditional_login:
    description: Allow autofill of passkeys in login page
    type: boolean
  rp:
    $ref: ./WebAuthConfigurationRp.yaml
  show_passkey_button:
    description: Show passkey button on login screen
    type: boolean
  timeout:
    $ref: ./WebAuthConfigurationTimeout.yaml
