type: object
properties:
  configs:
    description: List of MCP configurations
    type: array
    items:
      type: object
      $ref: ./mcpMcpConfig.yaml
  next_page_token:
    description: Pagination token to fetch the next page
    type: string
  prev_page_token:
    description: Pagination token to fetch the previous page
    type: string
  total_size:
    description: Total number of configs matching the filter
    type: integer
    format: int64
