type: object
properties:
  connection_tool_mappings:
    description: List of connection-to-tool mappings for this MCP config
    type: array
    items:
      type: object
      $ref: ./mcpMcpConfigConnectionToolMapping.yaml
  description:
    description: Description of the MCP configuration
    type: string
    examples:
      - Summarizes daily emails and posts to Slack
  id:
    description: Unique ID of the MCP config
    type: string
    readOnly: true
    examples:
      - cfg_85630864460904897
  name:
    description: Unique name for the MCP configuration
    type: string
    examples:
      - daily-summarizer
