type: object
properties:
  max_allowed_users:
    description: >-
      Maximum number of users allowed in the organization. When nil (not set),
      there feature is not enabled. When explicitly set to zero, it also means
      no limit. When set to a positive integer, it enforces the maximum user
      limit.
    type: integer
    format: int32
    examples:
      - 100
