description: >-
  Configuration options that control organization-level features and
  capabilities
type: object
title: Organization Settings
properties:
  features:
    description: >-
      List of feature toggles that control organization capabilities such as SSO
      authentication and directory synchronization
    type: array
    items:
      type: object
      $ref: ./organizationsOrganizationSettingsFeature.yaml
    examples:
      - - enabled: true
          name: sso
        - enabled: false
          name: directory_sync
examples:
  - features:
      - enabled: true
        name: sso
      - enabled: false
        name: directory_sync
