type: object
title: Rp contains relying party identifiers and origins
properties:
  ids:
    type: array
    title: >-
      Relying party IDs (derived from environment domain and verified custom
      domain)

      At least one required; must be hostnames without scheme or path
    items:
      type: string
  origins:
    type: array
    title: |-
      Allowed origins corresponding to the RP IDs (https://<domain>)
      At least one required; must be HTTPS origins
    items:
      type: string
