type: object
properties:
  login:
    description: Login timeout duration
    type: string
    default: '"300s"'
  login_uvd:
    description: Login timeout duration when user verification is discouraged
    type: string
    default: '"300s"'
  registration:
    description: Registration timeout duration
    type: string
    default: '"300s"'
  registration_uvd:
    description: Registration timeout duration when user verification is discouraged
    type: string
    default: '"300s"'
