type: object
properties:
  desired_authenticator_status:
    description: >-
      provides the list of statuses which are considered undesirable for status
      report validation purposes. Should be used with validate_status set to
      true.
    type: array
    items:
      type: string
      default: '[]'
  undesired_authenticator_status:
    description: >-
      provides the list of statuses which are considered undesirable for status
      report validation purposes. Should be used with validate_status set to
      true.
    type: array
    items:
      type: string
      default: >-
        ['ATTESTATION_KEY_COMPROMISE', 'USER_VERIFICATION_BYPASS',
        'USER_KEY_REMOTE_COMPROMISE', 'USER_KEY_PHYSICAL_COMPROMISE', 'REVOKED']
  validate_anchors:
    description: >-
      when set to true enables the validation of the attestation statement
      against the trust anchor from the metadata statement.
    type: boolean
  validate_attestation_type:
    description: >-
      when set to true enables the validation of the attestation statements type
      against the known types the authenticator can produce.
    type: boolean
  validate_entry:
    description: >-
      requires that the provided metadata has an entry for the given
      authenticator to be considered valid. By default an AAGUID which has a
      zero value should fail validation if validate_entry_permit_zero_aaguid is
      not provided with the value of true.
    type: boolean
  validate_entry_permit_zero_aaguid:
    description: >-
      is an option that permits a zero'd AAGUID from an attestation statement to
      automatically pass metadata validations. Generally helpful to use with
      validate_entry.
    type: boolean
  validate_status:
    description: >-
      when set to true enables the validation of the attestation statements
      AAGUID against the desired and undesired lists
    type: boolean
