/**
 * Sidebar Utilities
 * Helper functions for creating custom sidebar elements and path mapping
 */

import { normalizePath } from '../utils/path-matching'

// Type definitions for sidebar config items
interface SidebarItem {
  label?: string
  link?: string
  id?: string
  items?: (string | SidebarItem)[]
  autogenerate?: { directory: string }
  attrs?: Record<string, string>
}

/**
 * Recursively extracts all paths from sidebar items and maps them to a sidebar ID
 * Handles string paths, object paths with links, and nested items
 */
function extractPathsFromItems(
  items: (string | SidebarItem)[],
  sidebarId: string,
  map: Map<string, string>,
) {
  for (const item of items) {
    if (typeof item === 'string') {
      // String items are relative paths like 'authenticate/fsa/quickstart'
      const normalizedPath = normalizePath('/' + item)
      map.set(normalizedPath, sidebarId)
    } else if (item && typeof item === 'object') {
      // Object items may have a link property
      if (item.link && !item.link.startsWith('#')) {
        const normalizedPath = normalizePath(item.link)
        map.set(normalizedPath, sidebarId)
      }
      // Recursively process nested items
      if (item.items && Array.isArray(item.items)) {
        extractPathsFromItems(item.items, sidebarId, map)
      }
      // Handle autogenerate directories by storing the directory prefix
      if (item.autogenerate?.directory) {
        const dirPath = normalizePath('/' + item.autogenerate.directory)
        // Store with a special marker to indicate it's a prefix match
        map.set(`${dirPath}/*`, sidebarId)
      }
    }
  }
}

/**
 * Builds a Map of normalized paths to sidebar IDs from the sidebar configuration
 * This allows looking up which sidebar a given page path belongs to
 *
 * @param sidebarConfig - The sidebar configuration array from sidebar.config.ts
 * @returns Map where keys are normalized paths and values are sidebar IDs
 *
 * @example
 * ```ts
 * const pathToSidebar = buildPathToSidebarMap(sidebar)
 * const sidebarId = pathToSidebar.get('/authenticate/fsa/quickstart') // 'authenticate'
 * ```
 */
export function buildPathToSidebarMap(sidebarConfig: SidebarItem[]): Map<string, string> {
  const map = new Map<string, string>()

  for (const sidebar of sidebarConfig) {
    if (sidebar.id && sidebar.items) {
      extractPathsFromItems(sidebar.items, sidebar.id, map)
    }
  }

  return map
}

/**
 * Looks up which sidebar a path belongs to using the path-to-sidebar map
 * Handles both exact matches and prefix matches for autogenerated directories
 *
 * @param pathname - The path to look up
 * @param pathToSidebarMap - The map built by buildPathToSidebarMap
 * @returns The sidebar ID or null if not found
 */
export function getSidebarIdForPath(
  pathname: string,
  pathToSidebarMap: Map<string, string>,
): string | null {
  const normalizedPath = normalizePath(pathname)

  // First try exact match
  if (pathToSidebarMap.has(normalizedPath)) {
    return pathToSidebarMap.get(normalizedPath) || null
  }

  // Then try prefix matches for autogenerated directories
  for (const [pattern, sidebarId] of pathToSidebarMap.entries()) {
    if (pattern.endsWith('/*')) {
      const prefix = pattern.slice(0, -2) // Remove '/*'
      if (normalizedPath.startsWith(prefix + '/') || normalizedPath === prefix) {
        return sidebarId
      }
    }
  }

  return null
}

/**
 * Creates a horizontal divider in the sidebar
 * @returns A sidebar item configured as a visual separator
 * @example
 * ```ts
 * {
 *   label: 'User authentication',
 *   items: [...]
 * },
 * createDivider(),
 * {
 *   label: 'Authorization',
 *   items: [...]
 * }
 * ```
 */
export function createDivider() {
  return {
    label: '',
    link: '#',
    attrs: {
      'data-separator': 'divider',
      class: 'sidebar-divider',
      'aria-hidden': 'true',
      tabindex: '-1',
    },
  }
}

/**
 * Creates an uppercase section header in the sidebar
 * @param label - The text to display (will be automatically uppercased in CSS)
 * @returns A sidebar item configured as a section header
 * @example
 * ```ts
 * createSectionHeader('ESSENTIALS'),
 * {
 *   label: 'User authentication',
 *   items: [...]
 * }
 * ```
 */
export function createSectionHeader(label: string) {
  return {
    label,
    link: '#',
    attrs: {
      'data-separator': 'section-header',
      class: 'sidebar-section-header',
      'aria-hidden': 'true',
      tabindex: '-1',
    },
  }
}
