# Content Template Contract: AI-Driven MCP Auth Quickstart
# This contract defines the required structure for the MDX content template

openapi: 3.0.3
info:
  title: Content Template Schema Contract
  description: Required content structure for ai-assisted-mcp-quickstart.mdx template
  version: 1.0.0

components:
  schemas:
    ContentSection:
      type: object
      properties:
        type:
          type: string
          enum: ['introduction', 'prerequisites', 'steps', 'examples', 'next-steps']
        required:
          type: boolean
          default: false
        content:
          type: string
          description: Placeholder or template content

    ContentTemplate:
      type: object
      required:
        - introduction
        - prerequisites
        - steps
      properties:
        introduction:
          $ref: '#/components/schemas/ContentSection'
        prerequisites:
          $ref: '#/components/schemas/ContentSection'
        steps:
          type: array
          description: Sequential implementation steps
          minItems: 3
          items:
            type: object
            required:
              - title
              - description
            properties:
              title:
                type: string
                description: Step title using action verbs
              description:
                type: string
                description: Step description and purpose
              code:
                type: boolean
                description: Whether step includes code examples
                default: false
        examples:
          type: array
          description: Optional code example placeholders
          items:
            type: object
            properties:
              language:
                type: string
                enum: ['node', 'python', 'go', 'java']
              purpose:
                type: string
                description: What the example demonstrates
        nextSteps:
          $ref: '#/components/schemas/ContentSection'

paths: {}

# Contract Validation Rules:
# 1. Must include introduction section explaining the guide's purpose
# 2. Must include prerequisites section listing requirements
# 3. Must include at least 3 sequential steps
# 4. Must follow Scalekit documentation structure standards
# 5. Must use placeholder content ready for authoring
# 6. Must follow constitution writing standards (ted-docs philosophy)
# 7. Step titles must use imperative mood with action verbs
