# Frontmatter Contract: AI-Driven MCP Auth Quickstart
# This contract defines the required frontmatter structure for the new documentation page

openapi: 3.0.3
info:
  title: Frontmatter Schema Contract
  description: Required frontmatter structure for ai-assisted-mcp-quickstart.mdx
  version: 1.0.0

components:
  schemas:
    Frontmatter:
      type: object
      required:
        - title
        - description
        - sidebar
      properties:
        title:
          type: string
          maxLength: 60
          description: Page title for SEO and navigation
          example: 'AI-Driven MCP Auth Quickstart'
        description:
          type: string
          maxLength: 160
          description: Meta description for SEO
          example: 'Get started with AI-driven MCP authentication in your applications'
        sidebar:
          type: object
          required:
            - label
          properties:
            label:
              type: string
              description: Sidebar navigation label
              example: 'AI driven quickstart'
        tableOfContents:
          type: boolean
          description: Enable table of contents for multi-section pages
          default: true
          example: true

paths: {}

# Contract Validation Rules:
# 1. All required fields must be present
# 2. String lengths must not exceed limits
# 3. YAML syntax must be valid
# 4. Must follow constitution frontmatter standards
