# Sidebar Configuration Contract: MCP Auth Section
# This contract defines the required sidebar structure for adding the AI-driven quickstart

openapi: 3.0.3
info:
  title: Sidebar Configuration Contract
  description: Required sidebar structure for MCP Auth section with AI-driven quickstart
  version: 1.0.0

components:
  schemas:
    SidebarEntry:
      type: object
      required:
        - label
        - link
      properties:
        label:
          type: string
          description: Display text in sidebar navigation
          example: 'AI driven quickstart'
        link:
          type: string
          description: Relative path to documentation page
          pattern: '^authenticate/mcp/ai-assisted-mcp-quickstart$'
          example: 'authenticate/mcp/ai-assisted-mcp-quickstart'

    SidebarSection:
      type: object
      required:
        - label
        - id
        - items
      properties:
        label:
          type: string
          enum: ['MCP Auth']
          description: Section display name
        id:
          type: string
          enum: ['mcp']
          description: Section identifier
        items:
          type: array
          description: Array of sidebar items including the new AI-driven quickstart
          items:
            oneOf:
              - $ref: '#/components/schemas/SidebarEntry'
              - type: object # Other existing entries

paths: {}

# Contract Validation Rules:
# 1. New entry must be added to MCP Auth section (id: "mcp")
# 2. Entry must appear after existing quickstart entry
# 3. Label must be "AI driven quickstart"
# 4. Link must point to "authenticate/mcp/ai-assisted-mcp-quickstart"
# 5. TypeScript syntax must be valid
# 6. Must follow existing sidebar configuration patterns
